development:
  adapter: postgresql
  encoding: unicode
  database: sample_app_dev
  pool: 5
  username: timofiybilyi
  password: QAZwsx_193
  host: localhost

test: &test
    adapter: postgresql
    encoding: unicode
    database: sample_app_dev
    pool: 5
    username: timofiybilyi
    password: QAZwsx_193
    host: localhost

production:
    adapter: postgresql
    encoding: unicode
    database: sample_app_dev
    pool: 5
    username: timofiybilyi
    password: QAZwsx_193
    host: localhost

cucumber:
  <<: *test